clang and arm

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -34,40 +34,94 @@ jobs:
         run: |
           success=false
           # Compile with different C++ standards
-          if g++ -std=c++03 -Wall -Wextra -Werror -pedantic -c main.cpp -o gcc03; then
+          if g++ -std=c++03 -Wall -Wextra -Werror -pedantic -c main.cpp -o gcc03.o; then
             success=true
           fi
-          if g++ -std=c++11 -Wall -Wextra -Werror -pedantic -c main.cpp -o gcc11; then
+          if g++ -std=c++11 -Wall -Wextra -Werror -pedantic -c main.cpp -o gcc11.o; then
             success=true
           fi
-          if g++ -std=c++14 -Wall -Wextra -Werror -pedantic -c main.cpp -o gcc14; then
+          if g++ -std=c++14 -Wall -Wextra -Werror -pedantic -c main.cpp -o gcc14.o; then
             success=true
           fi
-          if g++ -std=c++17 -Wall -Wextra -Werror -pedantic -c main.cpp -o gcc17; then
+          if g++ -std=c++17 -Wall -Wextra -Werror -pedantic -c main.cpp -o gcc17.o; then
             success=true
           fi
-          if g++ -std=c++20 -Wall -Wextra -Werror -pedantic -c main.cpp -o gcc20; then
+          if g++ -std=c++20 -Wall -Wextra -Werror -pedantic -c main.cpp -o gcc20.o; then
             success=true
           fi
-          if g++ -std=c++23 -Wall -Wextra -Werror -pedantic -c main.cpp -o gcc23; then
+          if g++ -std=c++23 -Wall -Wextra -Werror -pedantic -c main.cpp -o gcc23.o; then
             success=true
           fi
-          if clang++ -std=c++03 -Wall -Wextra -Werror -pedantic -c main.cpp -o clang03; then
+          if clang++ -std=c++03 -Wall -Wextra -Werror -pedantic -c main.cpp -o clang03.o; then
             success=true
           fi
-          if clang++ -std=c++11 -Wall -Wextra -Werror -pedantic -c main.cpp -o clang11; then
+          if clang++ -std=c++11 -Wall -Wextra -Werror -pedantic -c main.cpp -o clang11.o; then
             success=true
           fi
-          if clang++ -std=c++14 -Wall -Wextra -Werror -pedantic -c main.cpp -o clang14; then
+          if clang++ -std=c++14 -Wall -Wextra -Werror -pedantic -c main.cpp -o clang14.o; then
             success=true
           fi
-          if clang++ -std=c++17 -Wall -Wextra -Werror -pedantic -c main.cpp -o clang17; then
+          if clang++ -std=c++17 -Wall -Wextra -Werror -pedantic -c main.cpp -o clang17.o; then
             success=true
           fi
-          if clang++ -std=c++20 -Wall -Wextra -Werror -pedantic -c main.cpp -o clang20; then
+          if clang++ -std=c++20 -Wall -Wextra -Werror -pedantic -c main.cpp -o clang20.o; then
             success=true
           fi
-          if clang++ -std=c++2b -Wall -Wextra -Werror -pedantic -c main.cpp -o clang23; then
+          if clang++ -std=c++2b -Wall -Wextra -Werror -pedantic -c main.cpp -o clang23.o; then
+            success=true
+          fi
+          # Exit with a non-zero status if none of the compilations succeeded
+          if ! $success; then
+            exit 1
+          fi
+
+      - name: generation IR code
+        run: |
+          success=false
+          # generate with different C++ standards
+          if clang++ -std=c++03 -Wall -Wextra -Werror -pedantic -S main.cpp -o clang03.s; then
+            success=true
+          fi
+          if clang++ -std=c++11 -Wall -Wextra -Werror -pedantic -S main.cpp -o clang11.s; then
+            success=true
+          fi
+          if clang++ -std=c++14 -Wall -Wextra -Werror -pedantic -S main.cpp -o clang14.s; then
+            success=true
+          fi
+          if clang++ -std=c++17 -Wall -Wextra -Werror -pedantic -S main.cpp -o clang17.s; then
+            success=true
+          fi
+          if clang++ -std=c++20 -Wall -Wextra -Werror -pedantic -S main.cpp -o clang20.s; then
+            success=true
+          fi
+          if clang++ -std=c++2b -Wall -Wextra -Werror -pedantic -S main.cpp -o clang23.s; then
+            success=true
+          fi
+          # Exit with a non-zero status if none of the generate succeeded
+          if ! $success; then
+            exit 1
+          fi
+
+      - name: Compile C++ code on arm
+        run: |
+          success=false
+          # Compile with different C++ standards on arm
+          if clang++ -std=c++03 -arch arm64 -Wall -Wextra -Werror -pedantic -c main.cpp -o clang03.o; then
+            success=true
+          fi
+          if clang++ -std=c++11 -Wall -arch arm64 -Wextra -Werror -pedantic -c main.cpp -o clang11.o; then
+            success=true
+          fi
+          if clang++ -std=c++14 -Wall -arch arm64 -Wextra -Werror -pedantic -c main.cpp -o clang14.o; then
+            success=true
+          fi
+          if clang++ -std=c++17 -Wall -arch arm64 -Wextra -Werror -pedantic -c main.cpp -o clang17.o; then
+            success=true
+          fi
+          if clang++ -std=c++20 -Wall -arch arm64 -Wextra -Werror -pedantic -c main.cpp -o clang20.o; then
+            success=true
+          fi
+          if clang++ -std=c++2b -Wall -arch arm64 -Wextra -Werror -pedantic -c main.cpp -o clang23.o; then
             success=true
           fi
           # Exit with a non-zero status if none of the compilations succeeded
